
namespace org.ternlang.event;

import org.ternlang.common.ExecuteStatus;
import org.ternlang.common.ProcessMode;

struct BeginEvent {
   status: ExecuteStatus;
   mode: ProcessMode;
   resource: char[100];
   process: char[20];
   project: char[20];
   system: char[20];
   pid: char[20];
   totalTime: long;
   totalMemory: long;
   usedMemory: long;
   threads: int;
   duration: long;
}

union Event {
   BeginEvent
}