
namespace com.bitril;

enum ProcessMode {
   REMOTE,
   SERVICE,
   SCRIPT,
   TASK
}

enum ExecuteStatus {
   REGISTERING,
   WAITING,
   STARTING,
   COMPILING,
   DEBUGGING,
   RUNNING,
   TERMINATING,
   FINISHED
}  

struct BeginEvent {
   status: ExecuteStatus;
   mode: ProcessMode;
   resource: char[100];
   process: char[20];
   project: char[20];
   system: char[20];
   pid: char[20];
   totalTime: long;
   totalMemory: long;
   usedMemory: long;
   threads: int;
   duration: long;
}

union Event {
   BeginEvent
}